---
title: "Hello and Welcome!"
author: "Ayaka Behro"
date: '2021-08-20'
tags: ["Aug-2021", "Life"]
categories: ["Life"]

featured: yes

# output:
#   blogdown::html_page:
#     toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

## Finally creating my own site!

After almost a year of deciding to create a personal website, it has finally come to fruition! After many months of playing around with various website generator platforms (notably Wordpress and Squarespace), I decided to do a 180 and use `R Blogdown`.   

There are several reasons for this: 

  * **Money**: most website generator platforms cost between [$6-50 per month](https://www.websitebuilderexpert.com/building-websites/how-much-should-a-website-cost/){target="_blank"} (for a basic subscription). As a (sort of) student, I want to cut costs where I can. 
  * **Skill**: While I am currently learning how to code HTML (slowly), I am nowhere near the skill necessary to code an entire personal website. That said, while I'm no HTML wiz, I do consider myself quite the R wizard. With a bit of research, a lot of patience and some learning I was able to put together this website. <small> (with many thanks to the various R forums and tutorials on the internet) </small>
  * **Practicality**: For the foreseeable future, I plan to be in the field of economic research or applied economics. After seeing many of my mentors and fellow economists develop similar websites, I wanted a platform suitable for research and academia Low and behold, the [Hugo Academic](https://wowchemy.com/){target="_blank"} theme! I found many website platforms catered to website platforms for companies and online shops, which is unfortunately unideal for my circumstances. 

As I continue developing my programming skills and contribute more to my website, I hope to refine certain elements and customize my site further. Which leads me to my next topic, *what is this site for*?

## Using this website to share my research, projects, and day-to-day life.

As a young economist and professional, I want a platform where I can share my research and interests with fellow economists and friends. That said, I am currently at a point in my career where I am exploring fields, economic areas and interests. Having completed my degree from UofT this year, I now have no such setting to "take courses" and learn new material. Therefore, I am taking it into my own hands and using this platform to share new research I develop and, admittedly, hold myself accountable. 

My goal is to create a new journal posts *at least* bi-weekly regarding either personal reflection, economic research or an op-ed on current topics. 